- Production|Iron and Steel|Steel|{steel_technology}:
    description: Production of Steel by {steel_technology} routes
    unit: Mt/yr

- Production|Non-Ferrous Metals|Aluminium|Primary:
    unit: Mt/yr
- Production|Non-Ferrous Metals|Aluminium|Secondary|New Scrap:
    unit: Mt/yr
- Production|Non-Ferrous Metals|Aluminium|Secondary|Old Scrap:
    unit: Mt/yr

- Production|Non-Metallic Minerals|Clinker:
    unit: Mt/yr
